version: 2

updates:
  - package-ecosystem: github-actions
    target-branch: dependencies
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: ci(gha)
    open-pull-requests-limit: 20
