name: Lint & Format

on:
  push:
    branches: [main]
  pull_request:
    branches: ["*"]
  workflow_dispatch:

permissions: {}

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Set PY env
        run: echo "PY=$(python -VV | sha256sum | cut -d' ' -f1)" >> $GITHUB_ENV

      - name: Cache pre-commit
        uses: actions/cache@v3
        with:
          path: ~/.cache/pre-commit/
          key: pre-commit|${{ env.PY }}|${{ hashFiles('.pre-commit-config.yaml') }}

      - name: Install LuaJIT
        uses: leafo/gh-actions-lua@v10
        with:
          luaVersion: "luajit-2.1.0-beta3"

      - name: Install LuaRocks
        uses: leafo/gh-actions-luarocks@v4.0.0

      - name: Install Luacheck
        run: luarocks install luacheck

      - name: Run pre-commit
        uses: pre-commit/action@v3.0.0
        with:
          extra_args: --verbose --all-files
