# https://www.hacksoft.io/blog/managing-dependencies-with-github-dependabot-and-actions

name: Automatic Rebase dependencies

on:
  push:
    branches:
      - main

permissions: {}

jobs:
  rebase:
    name: Rebase `dependencies` with `main`
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # otherwise, you will fail to push refs to dest repo
          ref: main
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git checkout dependencies || git checkout -b dependencies
          git rebase origin/main
          git push origin dependencies --force
