name: Update pre-commit config

on:
  schedule:
    - cron: "0 7 * * 1" # At 07:00 each Monday.
  workflow_dispatch:

permissions: {}

jobs:
  update-pre-commit:
    permissions:
      contents: write # for technote-space/create-pr-action to push code
      pull-requests: write # for technote-space/create-pr-action to create a PR
    name: Autoupdate pre-commit config
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v4

      - name: Cache multiple paths
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pre-commit
            ~/.cache/pip
          key: pre-commit-autoupdate-${{ runner.os }}-build

      - name: Update pre-commit config packages
        uses: technote-space/create-pr-action@v2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          EXECUTE_COMMANDS: |
            pip install pre-commit
            pre-commit autoupdate || (exit 0);
            pre-commit run -a || (exit 0);
          COMMIT_MESSAGE: "ci(pre-commit): bump hooks"
          PR_BRANCH_NAME: "dependencies"
          PR_TITLE: "ci(pre-commit): bump hooks"
